# Generated by Django 5.2 on 2025-04-18 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_remove_booking_user_booking_email_booking_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='format',
            field=models.CharField(choices=[('2D', '2D'), ('3D', '3D')], default='2D', max_length=10),
        ),
        migrations.AddField(
            model_name='movie',
            name='genre',
            field=models.CharField(choices=[('Action', 'Action'), ('Animation', 'Animation'), ('Biography', 'Biography'), ('Drama', 'Drama'), ('Horror', 'Horror'), ('Thriller', 'Thriller')], default='Drama', max_length=50),
        ),
        migrations.AddField(
            model_name='movie',
            name='language',
            field=models.CharField(choices=[('Chinese', 'Chinese'), ('English', 'English'), ('Hindi', 'Hindi'), ('Sinhala', 'Sinhala'), ('Tamil', 'Tamil')], default='English', max_length=20),
        ),
    ]
