# Generated by Django 5.2 on 2025-04-19 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_movie_format_movie_genre_movie_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='is_released',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(choices=[('Action', 'Action'), ('Adventure', 'Adventure'), ('Animation', 'Animation'), ('Biography', 'Biography'), ('Drama', 'Drama'), ('Horror', 'Horror'), ('Thriller', 'Thriller')], default='Drama', max_length=50),
        ),
    ]
