# Generated by Django 5.2 on 2025-04-20 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_booking_total_price_showtime_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='showtime',
            name='price',
        ),
        migrations.CreateModel(
            name='SeatCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('theater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat_categories', to='tickets.theater')),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='seat_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tickets.seatcategory'),
        ),
    ]
