# Generated by Django 5.2 on 2025-04-20 15:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_remove_showtime_price_seatcategory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='email',
            field=models.EmailField(default='guest@example.com', max_length=254, validators=[django.core.validators.EmailValidator(code='invalid_email', message='Please enter a valid email address')]),
        ),
        migrations.AlterField(
            model_name='booking',
            name='phone',
            field=models.CharField(default='0000000000', max_length=15, validators=[django.core.validators.RegexValidator(code='invalid_phone', message='Phone number must be 10 digits', regex='^\\d{10}$')]),
        ),
    ]
