# Generated by Django 5.2 on 2025-04-21 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0009_movie_cast_movie_director'),
    ]

    operations = [
        migrations.AddField(
            model_name='seatcategory',
            name='movie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tickets.movie'),
        ),
    ]
