# Generated by Django 5.2 on 2025-04-21 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0010_seatcategory_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
