# Generated by Django 5.2 on 2025-04-23 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0011_movie_is_featured'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seatcategory',
            old_name='price',
            new_name='price_2d',
        ),
        migrations.AddField(
            model_name='booking',
            name='format',
            field=models.CharField(choices=[('2D', '2D'), ('3D', '3D')], default='2D', max_length=10),
        ),
        migrations.AddField(
            model_name='seatcategory',
            name='price_3d',
            field=models.DecimalField(decimal_places=2, default=600.0, max_digits=6),
            preserve_default=False,
        ),
    ]
